services:

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:

      # KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      # Kafka listeners
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:29093

      # Addresses Kafka tells clients to use
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092

      # Controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Protocol mapping
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Single broker configuration
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge